# Generated by Django 3.2.9 on 2021-11-15 08:47

import apps.settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoUrl', models.FileField(default='', upload_to=apps.settings.models.wrapper)),
                ('welcomeText', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
