# Generated by Django 3.2.9 on 2021-11-14 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0008_alter_master_options'),
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.master')),
                ('testing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testing.testing')),
            ],
        ),
    ]
