# Generated by Django 3.2.9 on 2021-11-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_master_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
