# Generated by Django 3.2.9 on 2021-11-14 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_alter_master_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['id']},
        ),
    ]
